### ISSUE TITLE
Issue after upgrade to laravel 5.1

### ISSUE THREAD

**Issue by vDk3** [dawid-z/laravel-menu#1]
Hello, looks like there is issue with BladeExtension file after upgrade to laravel 5.1

`[2015-06-10 20:03:46] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\View\Compilers\BladeCompiler::CreatePlainMatcher()' in /vendor/lavary/laravel-menu/src/Lavary/Menu/Extensions/BladeExtension.php:36`

I hope you can fix that.

**Comment by dawid-z** [comment]
I hope this helps.
